In [1]:
# 1. ndarray与Python原生list运算效率对比
import random
import time
import numpy as np
a = []
for i in range(10000000):
    
    a.append(random.random())
    
t1 = time.time()
sum1=sum(a)
t2=time.time()

b=np.array(a)
t4=time.time()
sum3=np.sum(b)
t5=time.time()
print(t2-t1, t5-t4)

0.04691123962402344 0.020972490310668945


In [24]:
# 2. 创建一维数组

import numpy as np

list1 = [1,2,3,4]
oneArray = np.array(list1)
print(oneArray)
print(type(oneArray))
print(oneArray.shape)


t2 = np.array(range(10))
print(t2)
print(type(t2))

t3 = np.arange(0,10,2)
print(t3)
print(type(t3))

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 2 4 6 8]
<class 'numpy.ndarray'>


In [7]:
# 3. 创建二维数组
#读取数据源 numpy 
import numpy as np
list2 = [[1,2],[3,4],[5,6]]
print(list2)

twoArray = np.array(list2)
print(twoArray)
print(twoArray.shape)


[[1, 2], [3, 4], [5, 6]]
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [12]:
# 4. 常用属性
list2 = [[1,2],[3,4],[5,6]]

twoArray = np.array(list2)
# 获取数组的维度
print(twoArray.ndim)

# # 形状
print(twoArray.shape)

# 取行数
print(twoArray.shape[0])

# 取列数
print(twoArray.shape[1])


# # # 有多少个元素
print(twoArray.size)

2
(3, 2)
3
2
6


In [30]:
# 5. 调整数组的形状

four = np.array([[1,2,3],[4,5,6]]) 
print(four)
print(four.shape)
# 修改的是原有的
four.shape = (3,2)
print(four)

four_other = np.array([[1,2,3],[4,5,6]]) 

four_other_new = four.reshape(3,2)

print(four_other)
print(four_other_new)

# (6,)
# 将多维变成一维数组
five = four.reshape((6,),order='C')

# # # 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten(order='F')
print(five)
print(six)

t = np.arange(24)
print(t)
print(t.shape)
# # 转换成二维
t1 = t.reshape((4,6),order='C')
print(t1)
print(t1.shape)
# # 转成三维
t2 = t.reshape((2,3,4))
print(t2)
print(t2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [29]:
# 6. 将数组转成list
a= np.array([9, 12, 88, 14, 25])

list_a = a.tolist()
print(list_a)
print(type(list_a))

[9, 12, 88, 14, 25]
<class 'list'>


In [35]:
# 7. 数据类型
# np.int 默认是32位的
f = np.array([1,2,3,4,5], dtype = np.int)
# 返回数组中每个元素的字节单位长度
print(f.itemsize)
# 获取数据类型
print(f.dtype)

# 调整数据类型
# np.float 默认是64位的
f1 = f.astype(np.float)
print(f1.itemsize)
print(f1.dtype)

4
int32
8
float64


In [36]:
# 8. 一维数组的切片
import numpy as np
a = np.arange(10)

print(a)
# 冒号分隔切片参数 start:stop:step 来进行切片操作
print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2

# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[2],a)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
2 [0 1 2 3 4 5 6 7 8 9]


In [45]:
# 9. 多维数组的切片
#第一个重点
import numpy as np
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
# array[行,列]

print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的)
print(t1[1,:]) # 取一行
print('*'*20)

print(t1[1:])# 取连续的多行
print(t1[1:3,:])# 取连续的多行
print('*'*20)

print(t1[[0,2,3]])# 取不连续的多行
print(t1[[0,2,3],:])# 取不连续的多行
print('*'*20)

print(t1[:,1])# 取一列
print(t1[:,1:])# 连续的多列
print(t1[:,[0,2,3]])# 取不连续的多列
print(t1[2,3])# # 取某一个值,三行四列
print(t1[[0,1,1],[0,1,3]])# 取多个不连续的值，[[行，行。。。],[列，列。。。]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
15
[0 7 9]


In [51]:
# 10. 根据条件取值
#第二个重点:
t = np.arange(24).reshape(4,6)

print(t)


# 可以根据条件修改，比如讲小于10的值改掉
t[t<10]=0
print(t[t<10])
# #非0即真
# # 0 false 1true
# if 0: 
#     print('hahah')
# if '1010010': 
#     print('hehe')


t[(t>2)&(t<6)]=0   # 与  and or not 
t[(t<2)|(t>6)]=1   # 或
t[~(t>6)]=0   # 非
print(t)




[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  0  0  0  0  0]
 [ 0  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
# 暗号
import random
# 后八位
argot = ''
for index in range(4):
    argot = argot + str(random.randint(0,9))
print(argot)

In [58]:
# 11. 轴
import numpy as np

# 二维
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.sum(a))
#0轴是列 纵向取
print(np.sum(a,axis=0)) # [5 7 9]
#1轴是行 横向取
print(np.sum(a,axis = 1)) # [ 6 15]

# # 三维
a = np.arange(27).reshape((3,3,3))
print(a)

# print(np.sum(a, axis=0))
# print(np.sum(a, axis=1))
print(np.sum(a, axis=2))


[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


In [91]:
# 12. 数组的计算

# （1）数组与数的计算
t1 = np.arange(24).reshape((6,4))
print(t1)
print(t1+2)
print(t1*2)

# # （2）同种形状的数组(对应位置进行计算操作)
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(100,124).reshape((6,4))
print(t1)
print(t2)
print(t1+t2)
# print(t1*t2)

# （3）不种形状的多维数组不能计算
# t1 = np.arange(24).reshape((4,6))
# t2 = np.arange(6).reshape((2,3))
# print(t1)
# print(t2)
# print(t1-t2)

# （4）行数或者列数相同的一维数组和多维数组可以进行计算

# 行形状相同（会与每一行数组的对应位相操作)
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(0,6)
print(t1)
print(t2)
print(t1+t2)

# 行对行进行相加
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1)
print(t2)
print(t1+t2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5]
[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]
 [21 22 23 24 25 26]]


In [107]:
import numpy as np
score = np.array([[80,81],[75,86],[90,80]])
print(score)

# 获取最大值 最小值min()
print(score.max())
# 获取轴的最大值
print(score.max(axis=0))

# 获取平均值
print(score.mean())
# 获取轴的平均值
print(score.mean(axis = 0))
print(score.mean(axis = 1))

# 获取方差
print(score.var(axis = 1))

# 获取标准差
# 标准差是一组数组平均值的分散程度的度量。标准差越小代表数据越稳定
print(score.std(axis = 1))

# 获取极值。即最大值和最小值的差
print(score.ptp(axis=None))



[[80 81]
 [75 86]
 [90 80]]
90
[90 86]
82.0
[81.66666667 82.33333333]
[80.5 80.5 85. ]
[ 0.25 30.25 25.  ]
[0.5 5.5 5. ]
15


In [68]:
# 13. 数组添加
a = np.array([[1,2,3],[4,5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')

# append方法如果未指定axis参数，会把数组铺平，然后把数添加到后面
print ('向数组添加元素：')
print (np.append(a, [7,8,9]))
print ('\n')

 
print ('沿轴 0 添加元素：')
print (np.append(a, [[7,8,9],[10,11,12]],axis = 0))
print ('\n')
 
print ('沿轴 1 添加元素：')
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))
 

第一个数组：
[[1 2 3]
 [4 5 6]]


向数组添加元素：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [72]:
# 14. 函数在给定索引之前，沿给定轴在输入数组中插入值
a = np.array([[1,2],[3,4],[5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print (np.insert(a,3,[11,12]))
print ('\n')

print ('传递了 Axis 参数。 会广播值数组来配输入数组。')
 
print ('沿轴 0 广播：')
print (np.insert(a,1,[11,12],axis = 0))
print ('\n')
 
print ('沿轴 1 广播：')
print (np.insert(a,1,11,axis = 1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [108]:
# 15. 数组中的删除
#敲一遍,(研究0轴和一轴)

a = np.arange(12).reshape(3,4)
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print (np.delete(a,5))
print ('\n')
 
print ('删除每一行中的第二列：')
print (np.delete(a,1,axis = 1))
print ('\n')

print ('删除每一列中的第二行：')
print (np.delete(a,1,axis = 0))
print ('\n')

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除每一行中的第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


删除每一列中的第二行：
[[ 0  1  2  3]
 [ 8  9 10 11]]




In [118]:
a = np.array([5,2,6,2,7,5,9,2,8])
print(a)
print('\n')

# np.unique()用于去除数组中的重复元素
'''
如下参数：
arr：输入数组，如果不是一维数组则会展开
return_index:如果为true,返回新列表元素在旧列表元素下标位置，并以列表形式存储
return_inverse:如果为true，返回旧列表元素在新列表元素的下标位置，并以列表形式存储
return_counts:如果为true，返回去重数组在原数组中出现的次数
'''

u = np.unique(a)# 会自动进行升序排序
print(u)
print('\n')

x,index = np.unique(a,return_index=True)
print(x)
print(index)
print('\n')

y,index = np.unique(a,return_inverse=True)
print(y)
print(index)
print('\n')

count = np.unique(a,return_counts=True)
# print(z)
print(count)

[5 2 6 2 7 5 9 2 8]


[2 5 6 7 8 9]


[2 5 6 7 8 9]
[1 0 2 4 8 6]


[2 5 6 7 8 9]
[1 0 2 0 3 1 5 0 4]


(array([2, 5, 6, 7, 8, 9]), array([3, 2, 1, 1, 1, 1], dtype=int64))


In [90]:
# 16. 数组中的nan
# 创建一个nan
# a = np.nan
# print(a,type(a))

#特性:(1)float类型 
    #(2)nan != nan 返回True


# # --判断数组中为nan的个数(注意：float类型的数据才能赋值nan)

t = np.arange(24,dtype=float).reshape(4,6)
print(t)


# 可以使用np.count_nonzero() 来判断非零的个数，nan不是零值
#24条数据
print(np.count_nonzero(t))

# # 将三行四列的数改成nan
t[3,4] = np.nan
t[0,0] = np.nan

print(t)
print(np.count_nonzero(t))
# print(t)

#确定nan的个数

# # 注意： nan和任何数计算都为nan
# print(np.sum(t,axis=0))
# 0 == 0 
# if nan == nan :
# # 并且 np.nan != np.nan  结果 是TRUE

print(np.nan == np.nan)


# # 所以我们可以使用这两个结合使用判断nan的个数


#判断nan 的个数
# 提供方法
#nan != nan

# [1,2,3,4,5,nan]!= [1,2,3,4,5,nan]  # ----> [True,True...False] --- > [1,1,1,1,0]


print(np.count_nonzero(t[np.nan != np.nan]))
print(np.count_nonzero([1,1,1,1,0]))  #非0个数 所以是1个


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
23
[[nan  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]
24
False
24
4


In [108]:
#----------练习： 处理数组中nan
t = np.arange(24).reshape(4,6).astype('float') 
# 将数组中的一部分替换nan
t[1,3:] = np.nan
print(t)

#pandas 处理nan的方法


# # 遍历每一列，然后判断每一列是否有nan
for i in range(t.shape[1]):
# #获取当前列数据
    temp_col = t[:,i]
#     print(temp_col)
# # # 判断当前列的数据中是否含有nan
    nan_num = np.count_nonzero(temp_col != temp_col) 
    
    if nan_num != 0: # 条件成立说明含有nan

# # # 将这一列不为nan的数据拿出来
#         temp_col_not_nan = temp_col[temp_col==temp_col]
#         print(temp_col_not_nan)
# # # 将nan替换成这一列的平均值
#         print(temp_col[np.isnan(temp_col)])
#         temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)
        temp_col[np.isnan(temp_col)] = 0

print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  0.  0.  0.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [ ]:
np.isnan(temp_col)